apiVersion: v1
kind: ServiceAccount
metadata:
  name: imagepullsecret-patcher
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepullsecret-patcher
rules:
- apiGroups: [""]
  resources: ["namespaces", "serviceaccounts"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imagepullsecret-patcher
subjects:
- kind: ServiceAccount
  name: imagepullsecret-patcher
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: imagepullsecret-patcher
  apiGroup: rbac.authorization.k8s.io
